// @ts-check

/**
 * Shared data types for the BridgeJS fuzz testing infrastructure.
 *
 * BridgeType represents the type space we generate across.
 * Operations represent the composable steps in a test function body.
 * TestCase is the complete output of the smith, consumed by emitters.
 */

// ============================================================
// BridgeType — mirrors BridgeType in BridgeJSSkeleton.swift
// ============================================================

/**
 * @typedef {(
 *   | { kind: "int" }
 *   | { kind: "float" }
 *   | { kind: "double" }
 *   | { kind: "string" }
 *   | { kind: "bool" }
 *   | { kind: "jsObject" }
 *   | { kind: "void" }
 *   | { kind: "nullable", wrapped: BridgeType }
 *   | { kind: "array", element: BridgeType }
 *   | { kind: "dictionary", value: BridgeType }
 *   | { kind: "importedClass", name: string }
 * )} BridgeType
 */

// ============================================================
// Declarations — generated by DeclSmith
// ============================================================

/**
 * @typedef {{ label: string|null, name: string, type: BridgeType }} Param
 */

/**
 * An imported free function: @JSFunction func name(...) throws(JSException) -> ReturnType
 * @typedef {{
 *   name: string,
 *   params: Param[],
 *   returnType: BridgeType
 * }} ImportedFunc
 */

/**
 * An imported class (constructor-only for v1): @JSClass struct Name { @JSFunction init(...) }
 * @typedef {{
 *   name: string,
 *   constructorParams: Param[]
 * }} ImportedClass
 */

/**
 * The declaration environment — all available imported types and functions.
 * @typedef {{
 *   importedFuncs: ImportedFunc[],
 *   importedClasses: ImportedClass[]
 * }} DeclEnv
 */

// ============================================================
// Variables and Operations — generated by OpSmith
// ============================================================

/**
 * A variable in scope during code generation.
 * @typedef {{ name: string, type: BridgeType }} Var
 */

/**
 * @typedef {(
 *   | { kind: "literal", var: Var, jsValue: string }
 *   | { kind: "callImport", var: Var, func: ImportedFunc, args: Var[] }
 *   | { kind: "construct", var: Var, class: ImportedClass, args: Var[] }
 *   | { kind: "return", value: Var }
 * )} Operation
 */

// ============================================================
// TestFunc and TestCase — the complete smith output
// ============================================================

/**
 * A generated test function: @JS func name(params...) -> returnType { ops... }
 * @typedef {{
 *   name: string,
 *   params: Param[],
 *   returnType: BridgeType,
 *   ops: Operation[]
 * }} TestFunc
 */

/**
 * A complete test case — everything needed to emit Swift + JS for one iteration.
 * @typedef {{
 *   seed: number,
 *   env: DeclEnv,
 *   testFuncs: TestFunc[],
 *   jsExpected: Array<{ funcName: string, args: string[], expected: string }>
 * }} TestCase
 */

/**
 * @typedef {"compile-error"|"link-error"|"runtime-trap"|"runtime-error"|"wrong-result"} FailurePhase
 */

/**
 * @typedef {{
 *   id: string,
 *   phase: FailurePhase,
 *   fingerprint: string,
 *   timestamp: string,
 *   seed: number,
 *   typesInvolved: string[],
 *   error: string
 * }} FailureMetadata
 */

export {};
