#if canImport(BridgeJSSkeleton)
import BridgeJSSkeleton
#endif
#if canImport(BridgeJSUtilities)
import BridgeJSUtilities
#endif

/// Generates the Swift runtime's per-type ABI conformances from `BridgeABI`.
///
/// # Why this is generated
///
/// `Sources/JavaScriptKit/BridgeJSIntrinsics.swift` is the Swift half of the bridge: the
/// code that actually pushes and pops values on the typed stacks. The JS half is generated
/// by `BridgeJSLink` from `BridgeABI`. While the Swift half was hand-written, the two halves
/// were two independent implementations of one ABI, and nothing checked that they agreed --
/// a mismatch (say, pushing a payload before its tag on one side and after on the other) is
/// invisible to the snapshot suites, because each side stays perfectly self-consistent.
///
/// Generating both from `BridgeABI` removes that whole class of bug by construction rather
/// than by testing for it.
///
/// # What is and isn't generated
///
/// Only the conformances that fall out of a slot layout: the scalars, whose entire ABI is
/// "one slot, with a conversion". Their bodies are pure mechanism -- `Bool` is nothing but
/// `ABISlot("value", .i32, coerce: .boolToI32)` spelled in Swift.
///
/// Deliberately *not* generated, and still hand-written in `BridgeJSIntrinsics.swift`:
///
/// - The irreducible codec leaves (`String`, `JSObject`, `JSValue`) -- the compound `StackOp`
///   cases. `withRawJSValue` and UTF8 copying cannot be derived from a layout. They are the
///   leaves the description names but does not explain.
/// - The generic container defaults on `_BridgedSwiftStackType` (`bridgeJSStackPushAsArray`
///   and friends). Swift composes those at runtime via protocol dispatch, so there is one
///   generic implementation rather than one per type -- nothing to generate.
/// - Protocol declarations, closure/typed-array machinery.
///
/// # On the Swift spelling of conversions
///
/// `BridgeABI` says *which channel* a value travels on. It does not say how Swift spells the
/// conversion onto that channel -- `Int32(bitPattern: UInt32(self))` is Swift-backend
/// knowledge, exactly as `$0 >>> 0` is JS-backend knowledge. Both are driven by the same
/// `BridgeIntegerType` from the description; only the rendering differs.
public struct SwiftRuntimeABIEmitter {

    public init() {}

    /// The scalar types whose conformances are generated.
    ///
    /// Every one of these has a single-slot ABI, which is what makes them derivable. Types
    /// with multi-slot or irreducible ABIs are not in this list and stay hand-written.
    static let scalarTypes: [BridgeType] = [
        .bool,
        .integer(.int),
        .integer(.uint),
        .integer(.int8),
        .integer(.uint8),
        .integer(.int16),
        .integer(.uint16),
        .integer(.int32),
        .integer(.uint32),
        .integer(.int64),
        .integer(.uint64),
        .float,
        .double,
    ]

    public func render() throws -> String {
        let printer = CodeFragmentPrinter(
            header: """
                // swift-format-ignore-file
                //
                // ⚠️ DO NOT EDIT THIS FILE ⚠️
                //
                // Generated by `BridgeJSTool emit-intrinsics` from the ABI description in
                // `Plugins/BridgeJS/Sources/BridgeJSSkeleton/BridgeJSABI.swift`.
                // Run `./Utilities/bridge-js-generate.sh` to regenerate.
                //
                // These conformances are the Swift half of the BridgeJS stack ABI. The JavaScript
                // half is generated from the same description by BridgeJSLink, which is what keeps
                // the two sides in agreement. Editing this file by hand would reintroduce exactly
                // the drift that generating it removes -- change `BridgeJSABI.swift` instead.
                //
                // The types here are the ones whose ABI is a single slot plus a conversion.
                // Everything else -- String, JSObject, JSValue, the generic container defaults --
                // is irreducible and stays hand-written in `BridgeJSIntrinsics.swift`.
                """
        )
        printer.nextLine()

        for type in Self.scalarTypes {
            try renderScalar(type, into: printer)
            printer.nextLine()
        }

        return printer.lines.joined(separator: "\n") + "\n"
    }

    private func renderScalar(_ type: BridgeType, into printer: CodeFragmentPrinter) throws {
        let slot = try Self.singleSlot(of: type)
        let conv = try Self.conversion(for: type)
        let swiftType = try Self.swiftTypeName(of: type)
        let wasmType = try Self.wasmSwiftTypeName(of: slot)
        let channel = slot.channel.rawValue

        printer.write(
            "extension \(swiftType): _BridgedSwiftTypeLoweredIntoSingleWasmCoreType, _BridgedSwiftStackType {"
        )
        printer.indent {
            printer.write("// MARK: ImportTS")
            printer.write(
                "@_spi(BridgeJS) @_transparent public consuming func bridgeJSLowerParameter() -> \(wasmType) {"
            )
            printer.indent { printer.write(conv.lower) }
            printer.write("}")
            printer.write(
                "@_spi(BridgeJS) @_transparent public static func bridgeJSLiftReturn(_ value: \(wasmType)) -> \(swiftType) {"
            )
            printer.indent { printer.write(conv.lift) }
            printer.write("}")

            printer.write("// MARK: ExportSwift")
            printer.write(
                "@_spi(BridgeJS) @_transparent public static func bridgeJSLiftParameter(_ value: \(wasmType)) -> \(swiftType) {"
            )
            printer.indent { printer.write(conv.lift) }
            printer.write("}")
            printer.write("@_spi(BridgeJS) @_transparent public consuming func bridgeJSLowerReturn() -> \(wasmType) {")
            printer.indent { printer.write(conv.lower) }
            printer.write("}")

            printer.write("// MARK: Stack ABI")
            printer.write("@_spi(BridgeJS) public static func bridgeJSStackPop() -> \(swiftType) {")
            printer.indent { printer.write("bridgeJSLiftParameter(_swift_js_pop_\(channel)())") }
            printer.write("}")
            printer.write("@_spi(BridgeJS) public consuming func bridgeJSStackPush() {")
            printer.indent { printer.write("_swift_js_push_\(channel)(\(conv.lower))") }
            printer.write("}")
        }
        printer.write("}")
    }

    // MARK: - Deriving from the description

    /// The single slot a scalar occupies, per `BridgeABI`.
    ///
    /// This is the load-bearing line of the whole emitter: the channel is *read from the
    /// description*, not restated here. If the description says `Int` rides i32, this
    /// generates `_swift_js_push_i32`, and the JS side -- reading the same description --
    /// pops i32.
    static func singleSlot(of type: BridgeType) throws -> ABISlot {
        let slots = BridgeABI.payloadSlots(of: type)
        guard slots.count == 1, let slot = slots.first else {
            throw BridgeJSCoreError(
                "SwiftRuntimeABIEmitter only generates single-slot types, but \(type) has \(slots.count) slots"
            )
        }
        return slot
    }

    struct Conversion {
        /// Expression converting `self` down to the slot's Wasm type.
        let lower: String
        /// Expression lifting `value` from the slot's Wasm type back up.
        let lift: String
    }

    /// How Swift spells the conversion between a type and its slot.
    ///
    /// Driven by the same `BridgeIntegerType` the description carries; only the rendering is
    /// backend-specific. The rules are:
    ///
    /// - same width and signedness as the slot: no conversion at all
    /// - narrower than the slot: widen going down, `truncatingIfNeeded` coming back up
    /// - unsigned at the slot's width: reinterpret via `bitPattern` (the slot is signed)
    /// - unsigned word-sized: reinterpret through the fixed-width unsigned peer first
    static func conversion(for type: BridgeType) throws -> Conversion {
        switch type {
        case .bool:
            return Conversion(lower: "self ? 1 : 0", lift: "value == 1")
        case .float:
            return Conversion(lower: "Float32(self)", lift: "Float(value)")
        case .double:
            return Conversion(lower: "Float64(self)", lift: "Double(value)")
        case .integer(let t):
            return integerConversion(t)
        default:
            throw BridgeJSCoreError("No Swift conversion rule for \(type)")
        }
    }

    private static func integerConversion(_ t: BridgeIntegerType) -> Conversion {
        let swiftType = t.swiftTypeName
        // The Wasm channel is always signed (i32/i64); these are its Swift spellings.
        let signedWasm = t.is64Bit ? "Int64" : "Int32"
        let unsignedWasm = t.is64Bit ? "UInt64" : "UInt32"

        switch (t.width, t.isSigned) {
        case (.w32, true), (.w64, true):
            // Exactly the channel's type.
            return Conversion(lower: "self", lift: "value")
        case (.w32, false), (.w64, false):
            // Same width, opposite signedness: pure reinterpretation.
            return Conversion(
                lower: "\(signedWasm)(bitPattern: self)",
                lift: "\(swiftType)(bitPattern: value)"
            )
        case (.word, true):
            // Int is 32-bit on wasm32, but is a distinct type from Int32.
            return Conversion(lower: "\(signedWasm)(self)", lift: "\(swiftType)(value)")
        case (.word, false):
            // UInt has to cross both width and signedness, via its fixed-width peer.
            return Conversion(
                lower: "\(signedWasm)(bitPattern: \(unsignedWasm)(self))",
                lift: "\(swiftType)(\(unsignedWasm)(bitPattern: value))"
            )
        case (.w8, _), (.w16, _):
            // Narrower than the channel: widening down is lossless, so the cast is plain;
            // coming back up has to truncate, since the channel could hold anything.
            return Conversion(lower: "\(signedWasm)(self)", lift: "\(swiftType)(truncatingIfNeeded: value)")
        }
    }

    static func swiftTypeName(of type: BridgeType) throws -> String {
        switch type {
        case .bool: return "Bool"
        case .float: return "Float"
        case .double: return "Double"
        case .integer(let t): return t.swiftTypeName
        default: throw BridgeJSCoreError("No Swift type name for \(type)")
        }
    }

    /// The Swift spelling of a slot's Wasm core type. The spelling itself is
    /// `WasmCoreType.swiftType` -- the same one the thunk emitters use -- so the generated
    /// intrinsics cannot drift from the thunk signatures.
    static func wasmSwiftTypeName(of slot: ABISlot) throws -> String {
        guard let wasmCoreType = slot.wasmCoreType else {
            throw BridgeJSCoreError("\(slot.channel) is not a Wasm core channel")
        }
        return wasmCoreType.swiftType
    }
}
