EXPERIMENTAL_EMBEDDED_WASM=true swift build -c release --product EmbeddedApp \
  --triple wasm32-unknown-none-wasm  \
  -Xswiftc -enable-experimental-feature -Xswiftc Embedded \
  -Xswiftc -enable-experimental-feature -Xswiftc Extern \
  -Xswiftc -wmo -Xswiftc -disable-cmo \
  -Xswiftc -Xfrontend -Xswiftc -gnone \
  -Xswiftc -Xfrontend -Xswiftc -disable-stack-protector \
  -Xswiftc -cxx-interoperability-mode=default \
  -Xcc -D__Embedded -Xcc -fdeclspec \
  -Xlinker --export-if-defined=__main_argc_argv \
  -Xlinker --export-if-defined=swjs_call_host_function \
  -Xswiftc -Xclang-linker -Xswiftc -mexec-model=reactor