// swift-tools-version: 6.0

import CompilerPluginSupport
import PackageDescription

// SwiftExtract requires swift-syntax 603+ (SwiftLexicalLookup, SwiftIfConfig).
let swiftSyntaxVersion = Context.environment["BRIDGEJS_OVERRIDE_SWIFT_SYNTAX_VERSION"] ?? "603.0.0"

let package = Package(
    name: "BridgeJS",
    platforms: [.macOS(.v13)],
    dependencies: [
        .package(url: "https://github.com/swiftlang/swift-syntax", from: Version(swiftSyntaxVersion)!),
        // Development dependencies
        .package(url: "https://github.com/apple/swift-argument-parser", from: "1.7.0"),
    ],
    targets: [
        // SwiftExtract is swift-java's language-neutral Swift API extraction
        // layer, symlinked from a sibling swift-java checkout while the
        // BridgeJS adoption is developed against it.
        .target(
            name: "SwiftExtractConfigurationShared",
            path: "Sources/SwiftExtractConfigurationShared"
        ),
        .target(
            name: "SwiftExtract",
            dependencies: [
                "SwiftExtractConfigurationShared",
                .product(name: "SwiftBasicFormat", package: "swift-syntax"),
                .product(name: "SwiftIfConfig", package: "swift-syntax"),
                .product(name: "SwiftLexicalLookup", package: "swift-syntax"),
                .product(name: "SwiftParser", package: "swift-syntax"),
                .product(name: "SwiftSyntax", package: "swift-syntax"),
                .product(name: "SwiftSyntaxBuilder", package: "swift-syntax"),
            ],
            path: "Sources/SwiftExtract",
            resources: [
                // Checked-in build configuration for `#if` evaluation. In
                // swift-java this file is generated by _StaticBuildConfigPlugin;
                // here we ship a static default instead of carrying the plugin.
                .process("Resources")
            ],
            swiftSettings: [
                .swiftLanguageMode(.v5)
            ]
        ),
        .target(name: "BridgeJSBuildPlugin"),
        .executableTarget(
            name: "BridgeJSTool",
            dependencies: [
                "BridgeJSCore",
                "TS2Swift",
            ]
        ),
        .target(
            name: "TS2Swift",
            dependencies: [
                "BridgeJSCore",
                "BridgeJSSkeleton",
            ],
            exclude: ["JavaScript"]
        ),
        .target(
            name: "BridgeJSCore",
            dependencies: [
                "BridgeJSSkeleton",
                "BridgeJSUtilities",
                "SwiftExtract",
                .product(name: "SwiftParser", package: "swift-syntax"),
                .product(name: "SwiftSyntax", package: "swift-syntax"),
                .product(name: "SwiftBasicFormat", package: "swift-syntax"),
                .product(name: "SwiftSyntaxBuilder", package: "swift-syntax"),
            ]
        ),
        .target(name: "BridgeJSSkeleton"),
        .target(name: "BridgeJSUtilities"),

        .target(
            name: "BridgeJSLink",
            dependencies: [
                "BridgeJSSkeleton",
                "BridgeJSUtilities",
            ]
        ),

        .testTarget(
            name: "BridgeJSToolTests",
            dependencies: [
                "BridgeJSCore",
                "BridgeJSLink",
                "TS2Swift",
                .product(name: "SwiftParser", package: "swift-syntax"),
                .product(name: "SwiftSyntax", package: "swift-syntax"),
            ],
            exclude: ["__Snapshots__", "Inputs"]
        ),
        .macro(
            name: "BridgeJSMacros",
            dependencies: [
                .product(name: "SwiftSyntaxMacros", package: "swift-syntax"),
                .product(name: "SwiftCompilerPlugin", package: "swift-syntax"),
            ]
        ),
        .testTarget(
            name: "BridgeJSMacrosTests",
            dependencies: [
                "BridgeJSMacros",
                .product(name: "SwiftSyntaxMacrosGenericTestSupport", package: "swift-syntax"),
            ]
        ),

        .executableTarget(
            name: "BridgeJSToolInternal",
            dependencies: [
                "BridgeJSCore",
                "BridgeJSLink",
                .product(name: "ArgumentParser", package: "swift-argument-parser"),
            ]
        ),
    ]
)
