import JavaScriptKit

// This function is automatically generated by the @JS plugin
// It demonstrates how to use TypeScript functions and types imported from bridge.d.ts
@JS public func run() {
    // Call the imported consoleLog function defined in bridge.d.ts
    consoleLog("Hello, World!")

    // Get the document object - this comes from the imported getDocument() function
    let document = getDocument()

    // Access and modify properties - the title property is read/write
    document.title = "Hello, World!"

    // Access read-only properties - body is defined as readonly in TypeScript
    let body = document.body

    // Create a new element using the document.createElement method
    let h1 = document.createElement("h1")

    // Set properties on the created element
    h1.innerText = "Hello, World!"

    // Call methods on objects - appendChild is defined in the HTMLElement interface
    body.appendChild(h1)
}
