name: Performance

on: [pull_request]

jobs:
  perf:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: swiftwasm/setup-swiftwasm@v1
      - name: Run Benchmark
        run: |
          make bootstrap
          make perf-tester
          node ci/perf-tester
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
